#config_version=6

# Attract mode that starts when the machine boots up, stops
# whenever a game is started, and re-starts after the game ends.

mode_settings:
  selectable_items: #godot rada tikai tos, kas te ir rakstiti
    - title
    - credits
    - mpf_logo
  next_item_events: s_flipper_right_active
  previous_item_events: s_flipper_left_active

slide_player:
  mode_attract_started: attract

sound_player:
  mode_attract_started:
    select:
      bus: music