#config_version=6

switches:
  #Playfield_switches
  s_bumper_left:
    number:
  s_bumper_right:
    number:
  s_left_lane:
    number:
  # cabinet switches
  s_start:
    number:
    tags: start
  s_flipper_left:
    number:
    tags: left_flipper
  s_flipper_right:
    number:
    tags: right_flipper
  # trought switches
  s_trough_1:
    number:
  s_trough_2:
    number:
  s_trough_3:
    number:
  s_plunger_lane:
    number:
  