#config_version=6

switches:
  #Playfield_switches
  s_bumper_left:
    number: 1-0-3
  s_bumper_right:
    number: 1-0-8
  s_left_lane:
    number: 1-0-9
  # cabinet switches
  s_start:
    number: 1-0-10
    tags: start
  s_flipper_left:
    number: 1-0-1
    tags: left_flipper
  s_flipper_right:
    number: 1-0-2
    tags: right_flipper
  # trought switches
  s_trough_1:
    number: 3-0-16
    type: NC
  s_trough_2:
    number: 3-0-17
    type: NC
  s_trough_3:
    number: 3-0-18
    type: NC
  s_trough_4:
    number: 3-0-19
    type: NC
  s_trough_5:
    number: 3-0-20
    type: NC
  s_trough_6:
    number: 3-0-21
    type: NC
  s_trough_jam:
    number: 3-0-22
    type: NC
  s_plunger_lane:
    number: 3-0-23
  