#config_version=6

coils:
  c_trough_eject:
    number: 3-0-1
    default_pulse_ms: 20
  c_bumper_left:
    number: 3-0-2
    default_pulse_ms: 20
  c_bumper_right:
    number: 3-0-3
    default_pulse_ms: 20

  c_flipper_left:
    number: 1-0-1
    allow_enable: true
    default_hold_power: 0.125
    default_pulse_ms: 25
  c_flipper_right:
    number: 1-0-2
    allow_enable: true
    default_hold_power: 0.125
    default_pulse_ms: 25
  
  
autofire_coils:
  #Add your autofire cofigs for pops, slings, etc.
  ac_slingshot_left:
    coil: c_bumper_left
    switch: s_bumper_left
  ac_slingshot_right:
    coil: c_bumper_right
    switch: s_bumper_right

flippers:
  left_flipper:
    main_coil: c_flipper_left
    activation_switch: s_flipper_left
  right_flipper:
    main_coil: c_flipper_right
    activation_switch: s_flipper_right