#config_version=6

## MPF Main Machine Config File
#
# This file defines your system-wide properties like switches,
# drivers, ball devices, hardware platforms, and more. You can
# include everything here, or create sub-config files to be
# imported and merged with this one.

hardware:
  platform: opp
  driverboards: gen2


opp:
  #Use the USB ports defined by your OS for the two STM32 boards
  ports: COM3, COM4, COM5


config:
  - config_switches.yaml
  - config_coils.yaml
  - config_ball_devices.yaml
modes:
  - attract
  - base
  - bumpers

playfields:
  playfield:
    default_source_device: bd_trough
    tags: default

machine:
  balls_installed: 6 #How many balls are physically in your game
  min_balls: 1 #How few balls can be accounted for before you can start a game


game:
  balls_per_game: 1
  max_players: 1