#config_version=6

coils:
  c_trough_eject:
    number: 3-0-1
    default_pulse_ms: 20

  c_bumper_left:
    number: 3-0-2
    default_pulse_ms: 20
  
  c_bumper_right:
    number: 3-0-3
    default_pulse_ms: 20
  
autofire_coils:
  #Add your autofire cofigs for pops, slings, etc.
  ac_slingshot_left:
    coil: c_bumper_left
    switch: s_bumper_left
  ac_slingshot_right:
    coil: c_bumper_right
    switch: s_bumper_right